// Copyright (c) 2024 Bytedance Ltd. and/or its affiliates
// SPDX-License-Identifier: MIT

export class TextBISUConstants {
  static STYLE_FONT_WEIGHT = 'fontWeight'
  static STYLE_FONT_STYLE = 'fontStyle'
  static STYLE_TEXT_DECORATION = '-lark-textDecoration'
  static FONT_WEIGHT_BOLD = 'bold'
  static ITALIC = 'italic'
  static UNDERLINE = 'underline'
  static STRIKE_THROUGH = 'lineThrough'
}


